cameras:
- rtsp_url: test1.mp4
  detection_thresholds:
    head: 0.3
    helmet: 0.63
    body: 0.82
    vest: 0.43
    palm: 0.58
    glove: 0.34
    person: 0.65
- rtsp_url: test2.mp4
  detection_thresholds:
    head: 0.4
    helmet: 0.3
    body: 0.35
    vest: 0.3
    palm: 0.3
    glove: 0.2
    person: 0.75
- rtsp_url: test3.mp4
  detection_thresholds:
    head: 0.45
    helmet: 0.5
    body: 0.6
    vest: 0.5
    palm: 0.4
    glove: 0.3
    person: 0.7
- rtsp_url: test4.mp4
  detection_thresholds:
    head: 0.4
    helmet: 0.3
    body: 0.4
    vest: 0.3
    palm: 0.3
    glove: 0.2
    person: 0.7
