web_auth:
  login: victoria
  password: sama_ty_horoshaya
cameras:
- rtsp_url: rtsp://localhost:8554/stream1
  detection_thresholds:
    head: 0.36
    helmet: 0.54
    body: 0.48
    vest: 0.4
    palm: 0.3
    glove: 0.3
    person: 0.46
- rtsp_url: rtsp://localhost:8554/stream2
  detection_thresholds:
    head: 0.7
    helmet: 0.5
    body: 0.3
    vest: 0.3
    palm: 0.3
    glove: 0.5
    person: 0.4
- rtsp_url: rtsp://localhost:8554/stream3
  detection_thresholds:
    head: 0.3
    helmet: 0.5
    body: 0.6
    vest: 0.5
    palm: 0.4
    glove: 0.6
    person: 0.8
- rtsp_url: rtsp://localhost:8554/stream4
  detection_thresholds:
    head: 0.4
    helmet: 0.3
    body: 0.4
    vest: 0.3
    palm: 0.3
    glove: 0.3
    person: 0.6
- rtsp_url: rtsp://localhost:8554/stream25
  detection_thresholds:
    head: 0.6
    helmet: 0.5
    body: 0.6
    vest: 0.5
    palm: 0.4
    glove: 0.3
    person: 0.7
